Movies/Movie_App/urls.py
from django.urls import path, include

from Movie_App import views
app_name = 'movieapp'
urlpatterns = [
    path('',views.index,name="index"),
    path('movie/<int:MID>',views.details,name="details"),
    path('add/',views.add,name='add'),
    path('update/<int:Id>',views.update,name='update'),
    path('delete/<int:Id>',views.delete,name='delete')
]

Movies/Movies/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from Movies import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Movie_App.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Movies/Movie_App/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=200)
    desc = models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

Movies/Movie_App/forms.py
from django import  forms
from . models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

Movies/Movie_App/views.py
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie
# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list':movie
    }
    return  render(request,'index.html',context)


def details(request,MID):
    MV= Movie.objects.get(id=MID)
    return render(request,"details.html",{'movie':MV})


def add(request):
    if request.method=='POST':
        name=request.POST.get('Name',)
        year=request.POST.get('Year',)
        Description=request.POST.get('Description',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=Description,year=year,img=img)
        movie.save()
        return redirect('/')

    return render(request,'add.html')

def update(request,Id):
    movie = Movie.objects.get(id=Id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})


def delete(request,Id):
    if request.method == 'POST':
        MV = Movie.objects.get(id=Id)
        MV.delete()
        return redirect('/')
    return render(request,'delete.html')

Movies/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <h1>Add Movie</h1>
            <span style="color:red">
                 {% for msg in messages %}
            {{msg}}
            {% endfor %}
            </span>
            <hr>
            <label for="Name"><b>Name</b></label>
            <input type="text" placeholder="Enter Movie name" name="Name" id="Name" required><br>
            <label for="Year"><b>Release Year</b></label>
            <input type="text" placeholder="Release Year" name="Year" id="Year" required><br>
             <label for="Description"><b>Description</b></label>
            <textarea placeholder="Description" name="Description" id="Description" required></textarea><br>
            <label for="img"><b>Image</b></label>
            <input type="file" name="img" id="img"><br>
            <button class="btn btn-primary btn-lg active" type="submit" >ADD Movie</button>
        </div>

    </form>
{% endblock %}

Movies/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Movie</title>
    <link rel="icon" type="image/png" href="static/fev.png">
    <link rel="stylesheet" href="{% static 'style.css' %} ">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
  

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #669bbc;">
  <a class="navbar-brand" href="{% url 'movieapp:index' %}"><h3>Movie Details</h3></a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



    <a class="btn  active" style="float:right;margin-left:1100px;" href="{% url 'movieapp:add' %}" >Add New </a>
</nav>

  
{% block body %}
{% endblock %}
</body>
</html>

Movies/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div class="container"> 
<form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
  <h5>Are you sure you want to delete?</h5>
  <input class="btn btn-danger btn-lg active" type="submit" value="Delete">
</form>
</div>
{% endblock %}

Movies/templates/details.html
{% extends 'base.html' %}
{% block body %}

<div >
  <div class="container-x p-4">
  <img class="card-img-top" src="{{movie.img.url}}" alt="Card image cap" style="width: 15%; height: auto;">

  <div class="card-body">
    <h5 class="card-title">{{ movie.name }}</h5>
    <p class="card-text">{{ movie.desc }}</p>
  </div>

  <div class="card-body">
    <a class="btn btn-dark btn-lg active" href="{% url 'movieapp:update' movie.id %}" class="card-link">Update</a>
    <a class="btn btn-danger btn-lg active" href="{% url 'movieapp:delete' movie.id %}" class="card-link">Delete</a>
  </div>
  </div>
</div>

{% endblock %}

Movies/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
<input class="btn btn-primary btn-lg active" type="submit">
</form>
</div>
{% endblock %}

Movies/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3.5 p-4">
            <a href="{% url 'movieapp:details' i.id %}">
            <div class="card" style="width: 18rem;height: 45rem;padding:10px;">
                <img class="card-img-top" src="{{i.img.url}}" height="350px"  alt="Card image cap">
                <div class="card-body"> </a>
                  <h5 class="card-title">{{ i.name }}</h5>
                  <p class="card-text">{{i.desc}}</p>
                  <a href="{% url 'movieapp:details' i.id %}" class="btn btn-dark">{{ i.name }}</a>
                
                </div>
              </div>
            {% comment %} <div class="card" style="width: 18rem;padding:10px;">
              <img class="card-img-top" src="{{i.img.url}}"  height="450px" alt="Card image cap">
              <div class="card-body">
                  <a href="{% url 'movieapp:details' i.id %}"><h5 class="card-title">{{ i.name }}</h5></a>
              </div>
            </div> {% endcomment %}
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}